# lab-12/version-1-to-2.yml
# usage:
#   ansible-playbook version-1-to-2.yml --extra-vars "host=$USER"
---
- hosts: '{{ host }}'
  gather_facts: no
  become: true
  become_user: postgres

  tasks:

  - name: get database version
    community.postgresql.postgresql_query:
      db: cptr245
      query: SELECT version FROM "DbVersion"
    register: RESULT

  - name: add lastName column
    community.postgresql.postgresql_query:
      db: cptr245
      query: ALTER TABLE "Faculty" ADD COLUMN lastName text;
    when: "RESULT.query_result[0].version == 1"
